version: "3.8"

services:
  fb_frontend:
    build: ./front-end
    ports:
      - 8000:8000
    restart: unless-stopped
    environment:
      - VITE_SERVER_URL=http://127.0.0.1:3000/
    develop:
      watch:
        - path: ./front-end/package.json
          action: rebuild
        - path: ./front-end/package-lock.json
          action: rebuild
        - path: ./front-end
          target: /usr/src/app
          action: sync

    depends_on:
      - fb_backend

  fb_backend:
    build: ./back-end
    ports:
      - 3000:3000
    restart: unless-stopped
    develop:
      watch:
        - path: ./back-end/package.json
          action: rebuild
        - path: ./back-end/package-lock.json
          action: rebuild
        - path: ./back-end
          target: /usr/src/app
          action: sync
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://mongo:27017/facebook
      - REDIS_URL=redis://redis:6379
      - SALT_ROUNDS=10
      - TOKEN_SECRET=fkdsjfkjriewuorauiuries
      - TOKEN_EXPIRE_IN=10d
      - ENV=DEV
      - CLIENT=http://127.0.0.1:8000
      - SERVER_URL=http://127.0.0.1:3000
    depends_on:
      - mongo
      - redis 
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
  mongo:
    image: "mongo:latest"
    ports:
      - "27017:27017"
  nginx:
    build: ./nginx
    develop:
      watch:
        - path: ./nginx/nginx.conf
          target: /etc/nginx/conf.d/default.conf
          action: sync
    ports:
      - "80:80"
    depends_on:
      - fb_backend